### ISSUE TITLE
Milestone v0.5.0

### ISSUE THREAD

**Issue by giscafer** [1ziton/pixelmon#19]
# v0.5.0 里程碑功能介绍

## Pixelmon Packages

- **util** 工具包
- **cache** 缓存工具
- **acl** 角色权限控制
- **theme** 主题样式、管道、Services 等
- **pikachu** （皮卡丘）组件库，含基础通用组件&业务组件
- **ggeditor** 可视化图编辑器
- **mock** mock 测试数据，拦截 http 请求，生成随机数据
- **testing** 测试套件

## @pixelmon/pikachu

**要求** ：组件测试覆盖

- [x] 图片预览组件 Viewer
- [x] 上传组件
- [x] 表格组件 
- [] 地址选择组件
- [] Echarts 组件&指令
- [] G2组件&指令
- [] wysiwyg 编辑器（使用 [quill](https://github.com/KillerCodeMonkey/ngx-quill) 或者 [CKEditor](https://github.com/chymz/ng2-ckeditor) ，由于比较大，可以考虑抽离成独立模块，二不属于pikachu）

## @pixelmon/ggeditor 

- [x] Angular下实现 React Component 组件渲染，@pixelmon/ggeditor 

##  @pixelmon/theme 

- [] 主题定制页面

## @pixelmon/acl

- [] 符合业务权限系统控制调整

## @pixelmon/cache

- [] 检查是否需要调整

## @pixelmon/mock 

- [] 丰富一些 mock 数据接口，通用性，比如 [_mock](https://github.com/1ziton/pixelmon/blob/master/_mock)
